# Generated by Django 3.0.7 on 2020-06-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
