# Generated by Django 3.0.7 on 2020-06-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200617_2339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterModel',
            new_name='Register',
        ),
    ]
